### PR TITLE
Cgrooves/issue5

### LINKED ISSUE #4: Player tanks on main window
We need a couple of player tanks that we can drop into the main window. 

__Acceptance Criteria:__
- Player tank sprites/images selected and stored in a logical place in the repo
- Two player tanks of different colors displayed on the ground in the main window

### LINKED ISSUE #5: Controllable tank angle
__Acceptance Criteria:__
- Left/Right buttons can cause the tank's angle to increase and decrease (bounded at 0 and 180 degrees)
- We can visually see the tank turret moving and displaying the angle
- (optional) Text display of the angle on the HUD

### LINKED ISSUE #11: Tank Object
Object that resembles a tank.

Criteria:
- Tank body
- Controllable barrel

### PR DESCRIPTION
**Pull request by cgrooves**
Create a super simple tank class with a turret that you can control with left and right arrow buttons.

Recommended follow up:
- Implement the text display with a `arcade.gui.UILabel` instead
- Implement a full HUD
- Put a list of player tank objects in game (so you can designate one as "active" instead of hard-coding them)
- Make a more modular tank design, perhaps using sprites instead of primitive objects like lines and arcs

Closes #4, #5, #11

### CODE REVIEW

**Comment by cgrooves** [comment]
@TheSpy0 , whaddya think?

**Review by TheSpy0 — COMMENTED** [review]
Nice! Two players now.

**Review by TheSpy0 — COMMENTED** [review]
Looking good.

**Review by TheSpy0 — APPROVED** [review]
Approved!
I feel so powerful!

**Pull request merged**
